# META INFO
compend: 30.01.2050 22:00       # dd.mm.yyyy hh:mm        (24h format)

# Cogs
enable_map_alarm: False
enable_wr_alarm: False
enable_event_roles: False

# WR Alarm Settings
wr_channel_id: 1044146248422264852
event_roles_channel_id: 1044146248422264852


# DATABASE SETTINGS
dbhost:
dbport:
dbname:
# dbuser and dbpwd in secrets.yaml need to be set!

# Kacky DB settings
kdbhost:
kdbport:
kdbname:
# kdbuser and kdbpwd in secrets.yaml need to be set!

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: kacky_discord.log # might require absolute path
loglevel: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: Kacky_Discord_Bot
notify_admins_on_error: True
admins:
  - admin#1111
tm_server_admins:
  - admin#1111
