# META INFO
compend: 18.09.2022 22:00       # dd.mm.yyyy hh:mm        (24h format)

# Cogs
enable_map_alarm: True
map_alarm_quotes: True
map_alarm_quotes_freq: 12

# DATABASE SETTINGS
dbhost: localhost
dbport: 3306
dbname: kacky_backend
# dbuser and dbpwd in secrets.yaml need to be set!

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: kacky_discord.log # might require absolute path
loglevel: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: Kacky_Discord_Bot
notify_admins_on_error: True
admins:
  - corkscrew#0874
