# META INFO
compend: 02.04.2023 22:00       # dd.mm.yyyy hh:mm        (24h format)

# Cogs
enable_map_alarm: True
#enable_map_alarm: False
enable_wr_alarm: True
enable_event_roles: True

# WR Alarm Settings
wr_channel_id: 1052230458156519474
event_roles_channel_id: 1052230458156519474


# DATABASE SETTINGS
dbhost: localhost
dbport: 3306
dbname: kacky_backend_rebuild
# dbuser and dbpwd in secrets.yaml need to be set!

# Kacky DB settings
kdbhost: 116.202.114.119
kdbport: 3306
kdbname: kacky_kackiest
# kdbuser and kdbpwd in secrets.yaml need to be set!

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: kacky_discord.log # might require absolute path
loglevel: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: Kacky_Discord_Bot
notify_admins_on_error: True
admins:
  - corkscrew#0874
tm_server_admins:
  - corkscrew#0874
  - Kim#0786
